### ISSUE TITLE
w3-total-cache 0.10 - Fatal error  0.9.7.5 to 0.10 via WP CLI

### ISSUE THREAD

**Issue by novazembla** [W3EDGE/w3-total-cache#39]
Hello, 

When updating from 0.9.7.5 to 0.10 via WP Cli I'm getting unfortunately the following error. 

```
Fatal error: Uncaught Error: Call to undefined method W3TC\Util_Content::is_database_error() in /.../wp-content/plugins/w3-total-cache/Generic_Plugin.php:512
Stack trace:
#0 [internal function]: W3TC\Generic_Plugin->ob_callback('+--------------...', 9)
#1 /.../wp-includes/functions.php(4339): ob_end_flush()
#2 /.../wp-includes/class-wp-hook.php(286): wp_ob_end_flush_all('')
#3 /.../wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 /.../wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /.../wp-includes/load.php(954): do_action('shutdown')
#6 [internal function]: shutdown_action_hook()
#7 {main}
  thrown in /.../wp-content/plugins/w3-total-cache/Generic_Plugin.php on line 512
```
It seems not to cause any trouble. But I thought flagging it up might not do any bad. 

Thank you!

**Comment by maxicus** [comment]
Nice loading-order problem.

fixed by https://github.com/W3EDGE/w3-total-cache/commit/2068623608a253188f13d074ab1827feb76fcffb
