### ISSUE TITLE
Error 500 - Last version - robots.txt

### ISSUE THREAD

**Issue by Selven99** [W3EDGE/w3-total-cache#425]
Hi,

On my production with the latest version of Wordpress and W3TC, all files are readonly : it means the http user can't write robots.txt and try to request login form but crashes:
```
2021/09/08 19:54:13 [error] 887057#887057: *147 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function wp_create_nonce() in /var/www/domain.tld/releases/20210908174756/src/wp-includes/functions.php:1841
Stack trace:
#0 /var/www/domain.tld/releases/20210908174756/src/wp-admin/includes/file.php(2380): wp_nonce_field()
#1 /var/www/domain.tld/releases/20210908174756/src/wp-content/plugins/w3-total-cache/Util_WpFile.php(271): request_filesystem_credentials()
#2 /var/www/domain.tld/releases/20210908174756/src/wp-content/plugins/w3-total-cache/Util_WpFile.php(240): W3TC\Util_WpFile::request_filesystem_credentials()
#3 /var/www/domain.tld/releases/20210908174756/src/wp-content/plugins/w3-total-cache/Generic_Plugin.php(92): W3TC\Util_WpFile::file_exists()
#4 /var/www/domain.tld/releases/20210908174756/src/wp-content/plugins/w3-total-cache/Root_Loader.php(104): W3TC\Generic_Plugin->run()
#5 /var/www/domain.tld/releases/20210908174756/src/wp-conte" while reading response header from upstream, client: X.X.X.X, server: domain.tld, request: "GET /wp-admin/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/80_prod_domain_tld.sock:", host: "domain.tld"
```

After updating this module to the latest version and deploy the website, it seems to try to delete the robots.txt, and above error occurs. I tried to remove manually this robots.txt but error still here...

Someone had this issue?

I reported it because I'm not the only one to have a secured deployed version of Wordpress 🤔 

For now, I rollback this plugin update 

Thank you!

**Comment by Selven99** [comment]
I found a solution:

Add this line in wp-config.php: 
```// Fix WP Prompt issue
define('FS_METHOD','direct');
```

It force using filesystem and do not ask for ftp credentials.
In fact, it is not a problem because of read-only files!

:)
