### ISSUE TITLE
New file uploads being rejected because of W3TC CDN/AWS SDK error

### ISSUE THREAD

**Issue by Markshall** [W3EDGE/w3-total-cache#558]
When new images are being uploaded, the following error is being returned:

```The server cannot process the image. This can happen if the server is busy or does not have enough resources to complete the task. Uploading a smaller image may help. Suggested maximum size is 2,560 pixels.```

The image I'm uploading is only 24kb so I know the server resources aren't an issue.

I use AWS S3 for my CDN and have the CDN enabled within W3TC, and when I check my PHP error logs, I see the following:
```
[23-Sep-2022 10:14:32 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /var/www/html/website/wp-content/themes/mytheme/vendor/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 /var/www/html/website/wp-content/plugins/w3-total-cache/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()
#1 /var/www/html/website/wp-content/plugins/w3-total-cache/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#2 /var/www/html/website/wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(26): GuzzleHttp\Client->__construct()
#3 /var/www/html/website/wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/functions.php(279): Aws\Handler\GuzzleV6\GuzzleHandler->__construct()
#4 /var/www/html/website/wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/ClientResolver.php(652): Aws\default_http_handler()
#5 /var/www/html/website/wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/ClientRes in /var/www/html/website/wp-content/themes/mytheme/vendor/guzzlehttp/guzzle/src/functions.php on line 61
```

The files physically exist on my server once uploaded, but are not pushed to S3.

**Comment by Markshall** [comment]
On further inspection, this is not a W3TC issue. It is a conflict of versions of GuzzleHttp being used within my application.
